DATASET_CSV_PATH = "./kirov_okn_new.csv"
GEOJSON_POINTS_EXPORT_PATH = "./export.geojson"
MAP_EXPORT_PATH = "./index.html"
TARGET_GEOJSON_BORDERS = "./kirov_borders.geojson"
MARKER_SVG_PATH = "./map_marker.svg"
